// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5gbtNRx9_VXDYK9jFzO2eXYGyOS5ovdY',
    appId: '1:804209120358:web:062af8440a4c837e05c9a7',
    messagingSenderId: '804209120358',
    projectId: 'skill-path-8a04e',
    authDomain: 'skill-path-8a04e.firebaseapp.com',
    storageBucket: 'skill-path-8a04e.firebasestorage.app',
    measurementId: 'G-ZMXE6VEDRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJrf6-0CvszkPCTQhHnCp-05_ylrNvgg8',
    appId: '1:804209120358:android:dd60b7989007414b05c9a7',
    messagingSenderId: '804209120358',
    projectId: 'skill-path-8a04e',
    storageBucket: 'skill-path-8a04e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3BX-gcQBfCxRmh6EOfhgBOV6WHAm1_hw',
    appId: '1:804209120358:ios:bb463ff3b6f8df4905c9a7',
    messagingSenderId: '804209120358',
    projectId: 'skill-path-8a04e',
    storageBucket: 'skill-path-8a04e.firebasestorage.app',
    iosBundleId: 'com.example.skillPath',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3BX-gcQBfCxRmh6EOfhgBOV6WHAm1_hw',
    appId: '1:804209120358:ios:bb463ff3b6f8df4905c9a7',
    messagingSenderId: '804209120358',
    projectId: 'skill-path-8a04e',
    storageBucket: 'skill-path-8a04e.firebasestorage.app',
    iosBundleId: 'com.example.skillPath',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5gbtNRx9_VXDYK9jFzO2eXYGyOS5ovdY',
    appId: '1:804209120358:web:866602b5ab35130405c9a7',
    messagingSenderId: '804209120358',
    projectId: 'skill-path-8a04e',
    authDomain: 'skill-path-8a04e.firebaseapp.com',
    storageBucket: 'skill-path-8a04e.firebasestorage.app',
    measurementId: 'G-0HR5TVVCF6',
  );
}
